# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

test:
  secret_key_base: 4e4066d42b08e17dac3a54cef7cd6fbc28965039438bb8789e37a6b022cb6bd76d303f53af7f9f05a2d1645968a119bca4e0bb2ad2f5496c68608ef1f083a894

development:
  secret_key_base: 6eb92ba009e8f26fe69173f53a145bc4e0460a230de4ff6b361019570dfb13839f7b138edc284cd1f777a93b24c5b8b7b24e7413f205f8afcedda2e4c0b67c0d

testing:
  secret_key_base: 2d00b4e1fb5e981b25402cff4e3250baf856e146dda5da0d9bc2d74b674ec2866cb54abe655155dc5a03b3ae09901d1fe259bb2a853fbace1c92b3702486045e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
