
CREATE SEQUENCE "DATASTREAMPATHS_S1";
CREATE SEQUENCE "DIGITAL_OBJECTS_SEQ";
CREATE SEQUENCE "DPN_OBJECTS_SEQ";
CREATE SEQUENCE "DPN_REPLICAS_SEQ";
CREATE SEQUENCE "OBJECTPATHS_S1";

CREATE TABLE "DIGITAL_OBJECTS" (
"DIGITAL_OBJECT_ID" NUMBER(38,0) NOT NULL,
 "HOME_REPOSITORY" VARCHAR2(3) NOT NULL,
 CONSTRAINT SYS_C00163848 PRIMARY KEY (DIGITAL_OBJECT_ID)
);

CREATE TABLE "DPN_OBJECTS" (
"DPN_OBJECT_ID" NUMBER(38,0) NOT NULL,
 CONSTRAINT SYS_C00163850 PRIMARY KEY (DPN_OBJECT_ID)
);

CREATE TABLE "DPN_REPLICAS" (
"REPLICA_ID" NUMBER(38,0) NOT NULL,
 "DPN_OBJECT_ID" VARCHAR2(40) NOT NULL,
 "SUBMIT_DATE" TIMESTAMP(6) NOT NULL,
 "ACCEPT_DATE" TIMESTAMP(6) NOT NULL,
 "VERIFY_DATE" TIMESTAMP(6),
 CONSTRAINT SYS_C00163855 PRIMARY KEY (REPLICA_ID)
);

CREATE TABLE "REPLICAS" (
"REPLICA_ID" VARCHAR2(40) NOT NULL,
 "HOME_REPOSITORY" VARCHAR2(3) NOT NULL,
 "CREATE_DATE" TIMESTAMP(6) NOT NULL,
 "PAYLOAD_FIXITY_TYPE" VARCHAR2(7) NOT NULL,
 "PAYLOAD_FIXITY" VARCHAR2(64) NOT NULL,
 "PAYLOAD_SIZE" NUMBER(38,0) NOT NULL
);

CREATE TABLE "SCHEMA_MIGRATIONS" (
"VERSION" VARCHAR2(255) NOT NULL
);

CREATE UNIQUE INDEX "UNIQUE_SCHEMA_MIGRATIONS" ON "SCHEMA_MIGRATIONS" ("VERSION");

CREATE TABLE "SDR_OBJECTS" (
"SDR_OBJECT_ID" VARCHAR2(17) NOT NULL,
 "OBJECT_TYPE" VARCHAR2(20) NOT NULL,
 "GOVERNING_OBJECT" VARCHAR2(17),
 "OBJECT_LABEL" VARCHAR2(100),
 "LATEST_VERSION" NUMBER,
 CONSTRAINT SDR_OBJECTS_PK PRIMARY KEY (SDR_OBJECT_ID)
);

CREATE TABLE "SDR_OBJECT_VERSIONS" (
"SDR_OBJECT_ID" VARCHAR2(17) NOT NULL,
 "SDR_VERSION_ID" NUMBER NOT NULL,
 "INGEST_DATE" TIMESTAMP(6) WITH TIME ZONE,
 "REPLICA_ID" VARCHAR2(23),
 CONSTRAINT SDR_OBJECT_VERSIONS_PK PRIMARY KEY (SDR_OBJECT_ID,SDR_VERSION_ID)
);

CREATE TABLE "SDR_VERSION_STATS" (
"SDR_OBJECT_ID" VARCHAR2(17) NOT NULL,
 "SDR_VERSION_ID" NUMBER NOT NULL,
 "INVENTORY_TYPE" VARCHAR2(5) NOT NULL,
 "CONTENT_FILES" NUMBER NOT NULL,
 "CONTENT_BYTES" NUMBER NOT NULL,
 "CONTENT_BLOCKS" NUMBER NOT NULL,
 "METADATA_FILES" NUMBER NOT NULL,
 "METADATA_BLOCKS" NUMBER NOT NULL,
 "METADATA_BYTES" NUMBER,
 CONSTRAINT SDR_VERSION_STATS_PK PRIMARY KEY (SDR_OBJECT_ID,SDR_VERSION_ID,INVENTORY_TYPE)
);

CREATE TABLE "TAPE_ARCHIVES" (
"TAPE_ARCHIVE_ID" VARCHAR2(32) NOT NULL,
 "TAPE_SERVER" VARCHAR2(32) NOT NULL,
 "TAPE_NODE" VARCHAR2(32) NOT NULL,
 "SUBMIT_DATE" TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL  NOT NULL,
 "ACCEPT_DATE" TIMESTAMP(6) WITH TIME ZONE,
 "VERIFY_DATE" TIMESTAMP(6) WITH TIME ZONE,
 CONSTRAINT TAPE_ARCHIVE_SET_PK PRIMARY KEY (TAPE_ARCHIVE_ID)
);

CREATE TABLE "TAPE_REPLICAS" (
"REPLICA_ID" VARCHAR2(40) NOT NULL,
 "TAPE_ARCHIVE_ID" VARCHAR2(32) NOT NULL,
 CONSTRAINT TAPE_REPLICAS_PK PRIMARY KEY (REPLICA_ID,TAPE_ARCHIVE_ID)
);

ALTER TABLE "SDR_VERSION_STATS" ADD CONSTRAINT "SDR_VERSION_STATS_SDR_OBJ_FK1" FOREIGN KEY ("SDR_OBJECT_ID","SDR_VERSION_ID") REFERENCES "SDR_OBJECT_VERSIONS"("SDR_OBJECT_ID","SDR_VERSION_ID");


