
-- rails schema migrations

CREATE TABLE "SCHEMA_MIGRATIONS" (
"VERSION" VARCHAR2(255) NOT NULL
);
CREATE UNIQUE INDEX "UNIQUE_SCHEMA_MIGRATIONS" ON "SCHEMA_MIGRATIONS" ("VERSION") ;
  ALTER INDEX "UNIQUE_SCHEMA_MIGRATIONS" NOPARALLEL;



-- sequences

CREATE SEQUENCE "DATASTREAMPATHS_S1";
CREATE SEQUENCE "DIGITAL_OBJECTS_SEQ";
CREATE SEQUENCE "DPN_OBJECTS_SEQ";
CREATE SEQUENCE "DPN_REPLICAS_SEQ";
CREATE SEQUENCE "OBJECTPATHS_S1";


-- tables and constraints

CREATE TABLE "DIGITAL_OBJECTS" (
"DIGITAL_OBJECT_ID" NUMBER(38,0) NOT NULL,
 "HOME_REPOSITORY" VARCHAR2(3) NOT NULL
);
ALTER TABLE "DIGITAL_OBJECTS" ADD PRIMARY KEY ("DIGITAL_OBJECT_ID") ENABLE;

CREATE TABLE "DPN_OBJECTS" (
"DPN_OBJECT_ID" NUMBER(38,0) NOT NULL
);
ALTER TABLE "DPN_OBJECTS" ADD PRIMARY KEY ("DPN_OBJECT_ID") ENABLE;

CREATE TABLE "DPN_REPLICAS" (
"REPLICA_ID" NUMBER(38,0) NOT NULL,
 "DPN_OBJECT_ID" VARCHAR2(40) NOT NULL,
 "SUBMIT_DATE" TIMESTAMP(6) NOT NULL,
 "ACCEPT_DATE" TIMESTAMP(6) NOT NULL,
 "VERIFY_DATE" TIMESTAMP(6)
);
ALTER TABLE "DPN_REPLICAS" ADD PRIMARY KEY ("REPLICA_ID") ENABLE;

CREATE TABLE "REPLICAS" (
"REPLICA_ID" VARCHAR2(40) NOT NULL,
 "HOME_REPOSITORY" VARCHAR2(3) NOT NULL,
 "CREATE_DATE" TIMESTAMP(6) NOT NULL,
 "PAYLOAD_FIXITY_TYPE" VARCHAR2(7) NOT NULL,
 "PAYLOAD_FIXITY" VARCHAR2(64) NOT NULL,
 "PAYLOAD_SIZE" NUMBER(38,0) NOT NULL
);

CREATE TABLE "SDR_OBJECTS" (
"SDR_OBJECT_ID" VARCHAR2(17) NOT NULL,
 "OBJECT_TYPE" VARCHAR2(20) NOT NULL,
 "GOVERNING_OBJECT" VARCHAR2(17),
 "OBJECT_LABEL" VARCHAR2(100),
 "LATEST_VERSION" NUMBER
);
ALTER TABLE "SDR_OBJECTS" ADD CONSTRAINT "SDR_OBJECTS_PK"
  PRIMARY KEY ("SDR_OBJECT_ID") ENABLE;


CREATE TABLE "SDR_OBJECT_VERSIONS" (
"SDR_OBJECT_ID" VARCHAR2(17) NOT NULL,
 "SDR_VERSION_ID" NUMBER NOT NULL,
 "INGEST_DATE" TIMESTAMP(6) WITH TIME ZONE,
 "REPLICA_ID" VARCHAR2(23)
);
ALTER TABLE "SDR_OBJECT_VERSIONS" ADD CONSTRAINT "SDR_OBJECT_VERSIONS_PK"
  PRIMARY KEY ("SDR_OBJECT_ID", "SDR_VERSION_ID") ENABLE;


CREATE TABLE "SDR_VERSION_STATS" (
"SDR_OBJECT_ID" VARCHAR2(17) NOT NULL,
 "SDR_VERSION_ID" NUMBER NOT NULL,
 "INVENTORY_TYPE" VARCHAR2(5) NOT NULL,
 "CONTENT_FILES" NUMBER NOT NULL,
 "CONTENT_BYTES" NUMBER NOT NULL,
 "CONTENT_BLOCKS" NUMBER NOT NULL,
 "METADATA_FILES" NUMBER NOT NULL,
 "METADATA_BLOCKS" NUMBER NOT NULL,
 "METADATA_BYTES" NUMBER
);
ALTER TABLE "SDR_VERSION_STATS" ADD CONSTRAINT "SDR_VERSION_STATS_PK"
  PRIMARY KEY ("SDR_OBJECT_ID", "SDR_VERSION_ID", "INVENTORY_TYPE") ENABLE;
ALTER TABLE "SDR_VERSION_STATS" ADD CONSTRAINT "SDR_VERSION_STATS_SDR_OBJ_FK1"
  FOREIGN KEY ("SDR_OBJECT_ID","SDR_VERSION_ID")
  REFERENCES "SDR_OBJECT_VERSIONS"("SDR_OBJECT_ID","SDR_VERSION_ID");


CREATE TABLE "TAPE_ARCHIVES" (
"TAPE_ARCHIVE_ID" VARCHAR2(32) NOT NULL,
 "TAPE_SERVER" VARCHAR2(32) NOT NULL,
 "TAPE_NODE" VARCHAR2(32) NOT NULL,
 "SUBMIT_DATE" TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL  NOT NULL,
 "ACCEPT_DATE" TIMESTAMP(6) WITH TIME ZONE,
 "VERIFY_DATE" TIMESTAMP(6) WITH TIME ZONE
);
ALTER TABLE "TAPE_ARCHIVES" ADD CONSTRAINT "TAPE_ARCHIVE_SET_PK"
  PRIMARY KEY ("TAPE_ARCHIVE_ID") ENABLE;


CREATE TABLE "TAPE_REPLICAS" (
"REPLICA_ID" VARCHAR2(40) NOT NULL,
 "TAPE_ARCHIVE_ID" VARCHAR2(32) NOT NULL
);
ALTER TABLE "TAPE_REPLICAS" ADD CONSTRAINT "TAPE_REPLICAS_PK"
  PRIMARY KEY ("REPLICA_ID", "TAPE_ARCHIVE_ID") ENABLE;



-- rake db:structure:dump did not get this view

CREATE OR REPLACE FORCE VIEW "NEW_REPLICAS" ("REPLICA_ID", "HOME_REPOSITORY", "CREATE_DATE", "PAYLOAD_SIZE", "PAYLOAD_FIXITY_TYPE", "PAYLOAD_FIXITY") AS
  select  r.replica_id , r.home_repository, r.create_date , r.payload_size, r.payload_fixity_type,  r.payload_fixity
  from replicas r left join tape_replicas t on r.replica_id = t.replica_id
  where t.tape_archive_id is null;


-- Create indexes

CREATE UNIQUE INDEX "TAPE_ARCHIVE_SET_PK" ON "TAPE_ARCHIVES" ("TAPE_ARCHIVE_ID");
  ALTER INDEX "TAPE_ARCHIVE_SET_PK" NOPARALLEL;

CREATE UNIQUE INDEX "SDR_OBJECTS_PK" ON "SDR_OBJECTS" ("SDR_OBJECT_ID");
  ALTER INDEX "SDR_OBJECTS_PK" NOPARALLEL;

CREATE UNIQUE INDEX "SDR_OBJECT_VERSIONS_PK" ON "SDR_OBJECT_VERSIONS" ("SDR_OBJECT_ID", "SDR_VERSION_ID") ;
  ALTER INDEX "SDR_OBJECT_VERSIONS_PK" NOPARALLEL;

CREATE UNIQUE INDEX "SDR_VERSION_STATS_PK" ON "SDR_VERSION_STATS" ("SDR_OBJECT_ID", "SDR_VERSION_ID", "INVENTORY_TYPE") ;
  ALTER INDEX "SDR_VERSION_STATS_PK" NOPARALLEL;

CREATE UNIQUE INDEX "TAPE_REPLICAS_PK" ON "TAPE_REPLICAS" ("REPLICA_ID", "TAPE_ARCHIVE_ID") ;
  ALTER INDEX "TAPE_REPLICAS_PK" NOPARALLEL;




COMMIT;
END;

